### ISSUE TITLE
Training is not done properly (task 1.2)

### ISSUE THREAD

**Issue by shreyanshu28** [shreyanshu28/text-analysis#2]
I have set all the parameters correctly. There is a little confusion between what do I have to actually train, the vocab, all words, or the first 15 thousand most used words. For this reason, I am getting a key error in the third task.

**Comment by GlazunovianA** [comment]
Am tackling 1.2. As for your question, please refer to the Gensim documentation for further information. link: https://radimrehurek.com/gensim/models/word2vec.html
